# Reminder lead times in days.
# Reminders sent if object is before 11:59pm on `days` days from now.
# So 0 means anytime today, 1 means anytime today or tomorrow, etc.
reminder_lead_times:
  meal: 0
  statement: 5
  shift:
    head_cook: 3
    asst_cook: 2
    cleaner: 2
  cook_menu:
    early: 10
    late: 5
reminder_time_of_day: 6 # 6:00am
meal_reservation_default_length: 330 # mins
meal_reservation_default_prep_time: 180 # mins
